### ISSUE TITLE
Players Online Errors & Also Took More Than 7min untill next update 

### ISSUE THREAD

**Issue by TheWylot** [Alijkaz/IRMCTracker#12]
hey some times bot show us wrong player counter in .servers 
for example: we have a pinger bot  shows  139 Players but in tracker its 132 players fix it

**Comment by Alijkaz** [comment]
This is not an issue or misfunction,  Tracker is checking servers in a cycle and It would take some minutes (from 1 to 2 minutes) to update current players of a server so that It's not that high accurate as if Its a simple single server pinger bot
