### ISSUE TITLE
☠️SQL Injection....

### ISSUE THREAD

**Issue by Hopeful-ly** [Alijkaz/IRMCTracker#6]
I checked the code, and I think you wrote the SQLite command executer.
I'm pretty sure you are familiar with the phrase `SQL Injection`
Here's an example from your own code:

- I Type --  `.track madcraft`
- Your Code Executes -- `SELECT * FROM 'servers' WHERE name LIKE 'madcraft'`

Nothing unexpected happens, but because you put the raw input into the command, I can do almost anything....

- I Type -- `.track mad'{any_command_without_space} `
- Your Code Executes -- `SELECT * FROM 'servers' WHER name LIKE mad'{any_command_without_spaces}' `

And now anyone can execute anything in your database, and that's bad 🤦🏽 

I would suggest you using a premade framework that stops that from happening,
the one I'd suggest is: <a href="https://pypi.org/project/SQLAlchemy">SQLAlchemy</a>

**Comment by Alijkaz** [comment]
Will check that ASAP...

**Comment by Alijkaz** [comment]
Fixed the issue in the latest commit
